import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

enum AppLanguage { english, sheng }

class TranslationMaps {
  static const Map<String, String> en = {
    '1 minute': '1 minute',
    '1 second': '1 second',
    '10 seconds': '10 seconds',
    '16 items': '16 items',
    '20 seconds': '20 seconds',
    '3 Years': '3 Years',
    '3 seconds': '3 seconds',
    '30 seconds': '30 seconds',
    '32 items': '32 items',
    '4 items': '4 items',
    '5 minutes': '5 minutes',
    '5 seconds': '5 seconds',
    '8 items': '8 items',
    'About': 'About',
    'About ICHITO': 'About ICHITO',
    'Accent Color': 'Accent Color',
    'Account Recovery': 'Account Recovery',
    'Account Recovery Setup': 'Account Recovery Setup',
    'Add': 'Add',
    'Add Client': 'Add Client',
    'Add Contribution': 'Add Contribution',
    'Advanced Settings': 'Advanced Settings',
    'All data will be permanently deleted. The app will restart to the welcome screen.': 'All data will be permanently deleted. The app will restart to the welcome screen.',
    'Amount': 'Amount',
    'Analytics & Reports': 'Analytics & Reports',
    'Analytics Report': 'Analytics Report',
    'Any extra details, pockets, collar type...': 'Any extra details, pockets, collar type...',
    'App lock, biometrics, PIN': 'App lock, biometrics, PIN',
    'Appearance': 'Appearance',
    'Appearance Settings': 'Appearance Settings',
    'Apply gradients instead of solid colors': 'Apply gradients instead of solid colors',
    'Are you sure you want to discard this order? All progress will be lost.': 'Are you sure you want to discard this order? All progress will be lost.',
    'Auto-Lock Timeout': 'Auto-Lock Timeout',
    'Auto-Save Interval': 'Auto-Save Interval',
    'Auto-Save Notes': 'Auto-Save Notes',
    'Back': 'Back',
    'Backup': 'Backup',
    'Backup & Restore': 'Backup & Restore',
    'Backup Data': 'Backup Data',
    'Backup Summary': 'Backup Summary',
    'Backup created successfully': 'Backup created successfully',
    'Backup or restore data from device': 'Backup or restore data from device',
    'Backup restored successfully. Restarting app...': 'Backup restored successfully. Restarting app...',
    'Backups include your database, images, and all settings. They are stored as encrypted .zip files on your device.': 'Backups include your database, images, and all settings. They are stored as encrypted .zip files on your device.',
    'Balance': 'Balance',
    'Balance Due': 'Balance Due',
    'Built With': 'Built With',
    'Business / Shop Name': 'Business / Shop Name',
    'Business Email Address': 'Business Email Address',
    'Business Information': 'Business Information',
    'Business Name': 'Business Name',
    'Business Phone Number': 'Business Phone Number',
    'Business Profile': 'Business Profile',
    'Business Settings': 'Business Settings',
    'Business settings saved successfully': 'Business settings saved successfully',
    'CANCEL': 'CANCEL',
    'Cache': 'Cache',
    'Cache Management': 'Cache Management',
    'Cache cleared successfully': 'Cache cleared successfully',
    'Call': 'Call',
    'Camera': 'Camera',
    'Cancel': 'Cancel',
    'Centimeters (cm)': 'Centimeters (cm)',
    'Change': 'Change',
    'Change PIN or Password': 'Change PIN or Password',
    'Choose Photo': 'Choose Photo',
    'Clear': 'Clear',
    'Clear Cache': 'Clear Cache',
    'Clear Cache?': 'Clear Cache?',
    'Clear Date Filter': 'Clear Date Filter',
    'Client & Garment': 'Client & Garment',
    'Close': 'Close',
    'Color': 'Color',
    'Coming Soon': 'Coming Soon',
    'Configure global garment measurements': 'Configure global garment measurements',
    'Confirm Deletions': 'Confirm Deletions',
    'Confirm Reset': 'Confirm Reset',
    'Contact Support': 'Contact Support',
    'Continue': 'Continue',
    'Contributions': 'Contributions',
    'Could not launch WhatsApp': 'Could not launch WhatsApp',
    'Create Backup': 'Create Backup',
    'Creating Identity': 'Creating Identity',
    'Creating Orders': 'Creating Orders',
    'Creating backup...': 'Creating backup...',
    'Crop Photo': 'Crop Photo',
    'Currency': 'Currency',
    'Customer not found': 'Customer not found',
    'Customizing Your Theme': 'Customizing Your Theme',
    'DD/MM/YYYY': 'DD/MM/YYYY',
    'DELETE': 'DELETE',
    'Danger Zone': 'Danger Zone',
    'Dashboard Overview': 'Dashboard Overview',
    'Data Export': 'Data Export',
    'Database': 'Database',
    'Database backed up successfully!': 'Database backed up successfully!',
    'Date Created': 'Date Created',
    'Date Format': 'Date Format',
    'Debug & Logging': 'Debug & Logging',
    'Debug Logging': 'Debug Logging',
    'Debug log viewer - coming soon': 'Debug log viewer - coming soon',
    'Default Labor Cost': 'Default Labor Cost',
    'Default Measurements': 'Default Measurements',
    'Default Measurements (Optional)': 'Default Measurements (Optional)',
    'Default Sort Order': 'Default Sort Order',
    'Default View': 'Default View',
    'Default cost per order used in the order wizard pricing step': 'Default cost per order used in the order wizard pricing step',
    'Default measurements have not been recorded.': 'Default measurements have not been recorded.',
    'Delete Everything': 'Delete Everything',
    'Delete Note': 'Delete Note',
    'Delete all app data and reset to default settings. This cannot be undone.': 'Delete all app data and reset to default settings. This cannot be undone.',
    'Discard': 'Discard',
    'Discard Changes?': 'Discard Changes?',
    'Discard Order?': 'Discard Order?',
    'Display Preferences': 'Display Preferences',
    'Display, interaction & default sort': 'Display, interaction & default sort',
    'Does not match. Try again.': 'Does not match. Try again.',
    'Due Date': 'Due Date',
    'Due Date:': 'Due Date:',
    'Due Soon': 'Due Soon',
    'ERROR: The route ': 'ERROR: The route ',
    'EUR - Euro': 'EUR - Euro',
    'Edit': 'Edit',
    'Edit Type': 'Edit Type',
    'Edit/View': 'Edit/View',
    'Email': 'Email',
    'Email (Optional)': 'Email (Optional)',
    'Email Address': 'Email Address',
    'Enable App Lock (PIN)': 'Enable App Lock (PIN)',
    'Enable Biometrics': 'Enable Biometrics',
    'English': 'English',
    'Enter PIN': 'Enter PIN',
    'Enter measurements in inches. Existing profile data has been loaded automatically.': 'Enter measurements in inches. Existing profile data has been loaded automatically.',
    'Enter notes here...': 'Enter notes here...',
    'Example order number:': 'Example order number:',
    'Expected Total Amount': 'Expected Total Amount',
    'Export CSV': 'Export CSV',
    'Export PDF': 'Export PDF',
    'Export as CSV': 'Export as CSV',
    'Export as JSON': 'Export as JSON',
    'Export completed successfully': 'Export completed successfully',
    'Exporting CSV...': 'Exporting CSV...',
    'Exporting data as CSV...': 'Exporting data as CSV...',
    'Exporting data as JSON...': 'Exporting data as JSON...',
    'Factory Reset': 'Factory Reset',
    'Factory Reset?': 'Factory Reset?',
    'Female': 'Female',
    'Filter by Date': 'Filter by Date',
    'Financial Settings': 'Financial Settings',
    'Financial Summary': 'Financial Summary',
    'Financials': 'Financials',
    'Font Size': 'Font Size',
    'Forgot?': 'Forgot?',
    'Full Name *': 'Full Name *',
    'GBP - British Pound': 'GBP - British Pound',
    'Gallery': 'Gallery',
    'Garment not found': 'Garment not found',
    'Garments, Fabrics & Designs': 'Garments, Fabrics & Designs',
    'Gender *': 'Gender *',
    'Generating PDF Report...': 'Generating PDF Report...',
    'Go Home': 'Go Home',
    'Grid': 'Grid',
    'Grid Density': 'Grid Density',
    'Haptic Feedback': 'Haptic Feedback',
    'Help': 'Help',
    'Help & User Guide': 'Help & User Guide',
    'ICHITO': 'ICHITO',
    'Images': 'Images',
    'Inches': 'Inches',
    'Interaction Preferences': 'Interaction Preferences',
    'Invalid recovery details': 'Invalid recovery details',
    'KES - Kenya Shilling': 'KES - Kenya Shilling',
    'Labor Cost': 'Labor Cost',
    'Language': 'Language',
    'Language & Format': 'Language & Format',
    'Language & Format settings saved': 'Language & Format settings saved',
    'Language, units, currency & dates': 'Language, units, currency & dates',
    'Last Chance!': 'Last Chance!',
    'List': 'List',
    'Location': 'Location',
    'Location (Optional)': 'Location (Optional)',
    'Location / City': 'Location / City',
    'Lock App Now': 'Lock App Now',
    'Loyal': 'Loyal',
    'MM/DD/YYYY': 'MM/DD/YYYY',
    'Male': 'Male',
    'Managing Customers': 'Managing Customers',
    'Mark All Read': 'Mark All Read',
    'Material Cost': 'Material Cost',
    'Measurement Fields': 'Measurement Fields',
    'Measurement Types': 'Measurement Types',
    'Measurement Unit': 'Measurement Unit',
    'Measurements': 'Measurements',
    'Meeting Minutes / Notes': 'Meeting Minutes / Notes',
    'Meeting Title': 'Meeting Title',
    'Men': 'Men',
    'Most Used': 'Most Used',
    'Name': 'Name',
    'Never': 'Never',
    'New Order': 'New Order',
    'Newest': 'Newest',
    'Newest First': 'Newest First',
    'No Measurements': 'No Measurements',
    'No Notifications': 'No Notifications',
    'No clients found': 'No clients found',
    'No contributions yet': 'No contributions yet',
    'No description': 'No description',
    'No designs found.': 'No designs found.',
    'No fabrics found.': 'No fabrics found.',
    'No garments found': 'No garments found',
    'No measurement types added yet.': 'No measurement types added yet.',
    'No notes found': 'No notes found',
    'No orders found': 'No orders found',
    'No orders yet.': 'No orders yet.',
    'No payments recorded yet.': 'No payments recorded yet.',
    'No transactions found.': 'No transactions found.',
    'Note Settings': 'Note Settings',
    'Notes updated successfully': 'Notes updated successfully',
    'Notifications': 'Notifications',
    'Number of Orders': 'Number of Orders',
    'Oldest': 'Oldest',
    'Oldest First': 'Oldest First',
    'Open Source Licenses': 'Open Source Licenses',
    'Order Created!': 'Order Created!',
    'Order Number Prefix': 'Order Number Prefix',
    'Order Settings': 'Order Settings',
    'Order not found': 'Order not found',
    'Orders': 'Orders',
    'Owner Name': 'Owner Name',
    'PIN setup successfully!': 'PIN setup successfully!',
    'Password': 'Password',
    'Password must be at least 6 characters': 'Password must be at least 6 characters',
    'Password setup successfully!': 'Password setup successfully!',
    'Passwords do not match': 'Passwords do not match',
    'Payment History': 'Payment History',
    'Percentage tax applied to order totals (0 = no tax)': 'Percentage tax applied to order totals (0 = no tax)',
    'Performance': 'Performance',
    'Performance Mode': 'Performance Mode',
    'Personal & business information': 'Personal & business information',
    'Phone': 'Phone',
    'Phone *': 'Phone *',
    'Phone Number': 'Phone Number',
    'Photo update coming soon': 'Photo update coming soon',
    'Pick Accent Color': 'Pick Accent Color',
    'Pinch to zoom, drag to position': 'Pinch to zoom, drag to position',
    'Please enter a code and select date of birth': 'Please enter a code and select date of birth',
    'Please pick a valid backup file.': 'Please pick a valid backup file.',
    'Please select a Due Date': 'Please select a Due Date',
    'Please select at least one measurement field.': 'Please select at least one measurement field.',
    'Preferences': 'Preferences',
    'Preferences Settings': 'Preferences Settings',
    'Preferences are applied immediately to your view. Sort preferences affect how lists are displayed.': 'Preferences are applied immediately to your view. Sort preferences affect how lists are displayed.',
    'Privacy Policy': 'Privacy Policy',
    'Profile': 'Profile',
    'Profile Settings': 'Profile Settings',
    'Profile saved successfully!': 'Profile saved successfully!',
    'Recent': 'Recent',
    'Recently Added': 'Recently Added',
    'Recipient (Who receives today?)': 'Recipient (Who receives today?)',
    'Record': 'Record',
    'Record Payment': 'Record Payment',
    'Recovery info saved': 'Recovery info saved',
    'Regular': 'Regular',
    'Require PIN or Biometrics on startup': 'Require PIN or Biometrics on startup',
    'Required Measurements': 'Required Measurements',
    'Reset': 'Reset',
    'Restore': 'Restore',
    'Restore Backup?': 'Restore Backup?',
    'Restore Data': 'Restore Data',
    'Restore database from a backup file.': 'Restore database from a backup file.',
    'Restore from Backup': 'Restore from Backup',
    'Restoring backup...': 'Restoring backup...',
    'Restoring from backup will REPLACE all current data. This action cannot be undone.': 'Restoring from backup will REPLACE all current data. This action cannot be undone.',
    'Revenue Trend (Last 6 Months)': 'Revenue Trend (Last 6 Months)',
    'Role / Status': 'Role / Status',
    'Rotate Left': 'Rotate Left',
    'Rotate Right': 'Rotate Right',
    'Route Not Found': 'Route Not Found',
    'SMS': 'SMS',
    'Sample Text Preview': 'Sample Text Preview',
    'Save': 'Save',
    'Save Business Settings': 'Save Business Settings',
    'Save Changes': 'Save Changes',
    'Save Note': 'Save Note',
    'Save Password': 'Save Password',
    'Save Recovery Details': 'Save Recovery Details',
    'Save Settings': 'Save Settings',
    'Save a copy of your database to local storage.': 'Save a copy of your database to local storage.',
    'Search by Order # or Client...': 'Search by Order # or Client...',
    'Search by name or phone...': 'Search by name or phone...',
    'Search designs...': 'Search designs...',
    'Search fabrics...': 'Search fabrics...',
    'Search garments...': 'Search garments...',
    'Search notes...': 'Search notes...',
    'Search transactions...': 'Search transactions...',
    'Security': 'Security',
    'Security & Backup': 'Security & Backup',
    'Security Settings': 'Security Settings',
    'Select': 'Select',
    'Select Currency': 'Select Currency',
    'Select Date Format': 'Select Date Format',
    'Select Language': 'Select Language',
    'Select Unit': 'Select Unit',
    'Select a source for your profile photo': 'Select a source for your profile photo',
    'Sermon Title': 'Sermon Title',
    'Set memorable date for password reset': 'Set memorable date for password reset',
    'Set up recovery details to regain access if you forget your PIN or Password.': 'Set up recovery details to regain access if you forget your PIN or Password.',
    'Settings': 'Settings',
    'Setup Security': 'Setup Security',
    'Sheng': 'Sheng',
    'Show Full Order Numbers': 'Show Full Order Numbers',
    'Sort Customers By': 'Sort Customers By',
    'Sort Notes By': 'Sort Notes By',
    'Sort Orders By': 'Sort Orders By',
    'Sort: ': 'Sort: ',
    'Special Instructions / Notes': 'Special Instructions / Notes',
    'Spent': 'Spent',
    'Start by adding your first customer and creating an order.': 'Start by adding your first customer and creating an order.',
    'Start typing...': 'Start typing...',
    'Status': 'Status',
    'Step 1: Select Client': 'Step 1: Select Client',
    'Step 2: Select Garment': 'Step 2: Select Garment',
    'Step 4: Materials & Design': 'Step 4: Materials & Design',
    'Step 5: Pricing & Scheduling': 'Step 5: Pricing & Scheduling',
    'Step 6: Review & Confirm': 'Step 6: Review & Confirm',
    'Storage Management': 'Storage Management',
    'TZS - Tanzania Shilling': 'TZS - Tanzania Shilling',
    'Taking Notes': 'Taking Notes',
    'Tap to change the primary accent color': 'Tap to change the primary accent color',
    'Tax Rate (%)': 'Tax Rate (%)',
    'The complete offline management system designed specifically for tailors.': 'The complete offline management system designed specifically for tailors.',
    'The feature ': 'The feature ',
    'The order has been successfully recorded in the system.': 'The order has been successfully recorded in the system.',
    'Theme, colors, and gradients': 'Theme, colors, and gradients',
    'This item will be permanently deleted. This action cannot be undone. Please confirm by entering your PIN or using biometrics.': 'This item will be permanently deleted. This action cannot be undone. Please confirm by entering your PIN or using biometrics.',
    'This will delete ALL data including customers, orders, notes, and images. This action CANNOT be undone.': 'This will delete ALL data including customers, orders, notes, and images. This action CANNOT be undone.',
    'This will delete cached image thumbnails. The app will regenerate them on next use.': 'This will delete cached image thumbnails. The app will regenerate them on next use.',
    'Title': 'Title',
    'Title A-Z': 'Title A-Z',
    'Title Z-A': 'Title Z-A',
    'Toggle View': 'Toggle View',
    'Total Amount': 'Total Amount',
    'Total Collected: ': 'Total Collected: ',
    'Total Expected': 'Total Expected',
    'Total Paid': 'Total Paid',
    'Total Spent': 'Total Spent',
    'Total Used': 'Total Used',
    'Transaction Details': 'Transaction Details',
    'Trial Date': 'Trial Date',
    'Trial Date:': 'Trial Date:',
    'Trial/Fitting Date': 'Trial/Fitting Date',
    'Type ': 'Type ',
    'Type RESET': 'Type RESET',
    'UGX - Uganda Shilling': 'UGX - Uganda Shilling',
    'USD - US Dollar': 'USD - US Dollar',
    'Understanding Statistics': 'Understanding Statistics',
    'Unisex': 'Unisex',
    'Unlock': 'Unlock',
    'Upload': 'Upload',
    'Use Gradient Accents': 'Use Gradient Accents',
    'Use fingerprint or face unlock': 'Use fingerprint or face unlock',
    'User guide and support': 'User guide and support',
    'VIP': 'VIP',
    'Verify & Unlock': 'Verify & Unlock',
    'Version info and legal': 'Version info and legal',
    'View All': 'View All',
    'View Debug Logs': 'View Debug Logs',
    'View Order': 'View Order',
    'View Payment Details': 'View Payment Details',
    'View:': 'View:',
    'Warning: Advanced settings are for experienced users. Incorrect changes may cause unexpected behavior.': 'Warning: Advanced settings are for experienced users. Incorrect changes may cause unexpected behavior.',
    'Welcome to ICHITO': 'Welcome to ICHITO',
    'Welcome to ICHITO!': 'Welcome to ICHITO!',
    'What type of note?': 'What type of note?',
    'Women': 'Women',
    'Write notes here...': 'Write notes here...',
    'Write sermon notes here...': 'Write sermon notes here...',
    'YYYY-MM-DD': 'YYYY-MM-DD',
    'You have unsaved changes. Are you sure you want to discard them?': 'You have unsaved changes. Are you sure you want to discard them?',
    'e.g. 0712 345 678': 'e.g. 0712 345 678',
    'e.g. Chest, Waist, Length': 'e.g. Chest, Waist, Length',
    'e.g. Jane Muthoni': 'e.g. Jane Muthoni',
    'e.g. Nairobi CBD': 'e.g. Nairobi CBD',
    'e.g. jane@email.com': 'e.g. jane@email.com',
    'e.g., +254 712 345 678': 'e.g., +254 712 345 678',
    'e.g., Ichito Studios': 'e.g., Ichito Studios',
    'e.g., Nairobi, Kenya': 'e.g., Nairobi, Kenya',
    'e.g., contact@ichito.app': 'e.g., contact@ichito.app',
  };

  static const Map<String, String> sheng = {
    '1 minute': '1 minute',
    '1 second': '1 second',
    '10 seconds': '10 seconds',
    '16 items': '16 items',
    '20 seconds': '20 seconds',
    '3 Years': '3 Years',
    '3 seconds': '3 seconds',
    '30 seconds': '30 seconds',
    '32 items': '32 items',
    '4 items': '4 items',
    '5 minutes': '5 minutes',
    '5 seconds': '5 seconds',
    '8 items': '8 items',
    'About': 'About',
    'About ICHITO': 'About ICHITO',
    'Accent Color': 'Accent Color',
    'Account Recovery': 'Account Recovery',
    'Account Recovery Setup': 'Account Recovery Setup',
    'Add': 'Weka',
    'Add Client': 'Weka Mteja',
    'Add Contribution': 'Weka Contribution',
    'Advanced Settings': 'Advanced Masetting',
    'All data will be permanently deleted. The app will restart to the welcome screen.': 'All data will be permanently deleted. The app will restart to the welcome screen.',
    'Amount': 'Amount',
    'Analytics & Reports': 'Mahesabu & Reports',
    'Analytics Report': 'Mahesabu Report',
    'Any extra details, pockets, collar type...': 'Any extra details, pockets, collar type...',
    'App lock, biometrics, PIN': 'App lock, Kidole, Namba Siri',
    'Appearance': 'Vile Inabamba',
    'Appearance Settings': 'Vile Inabamba Masetting',
    'Apply gradients instead of solid colors': 'Apply gradients instead of solid colors',
    'Are you sure you want to discard this order? All progress will be lost.': 'Are you sure you want to discard this order? All progress will be lost.',
    'Auto-Lock Timeout': 'Auto-Lock Timeout',
    'Auto-Save Interval': 'Auto-Save Interval',
    'Auto-Save Notes': 'Auto-Save Riba',
    'Back': 'Back',
    'Backup': 'Backup',
    'Backup & Restore': 'Backup & Restore',
    'Backup Data': 'Backup Data',
    'Backup Summary': 'Backup Summary',
    'Backup created successfully': 'Backup created successfully',
    'Backup or restore data from device': 'Backup or restore data from device',
    'Backup restored successfully. Restarting app...': 'Backup restored successfully. Restarting app...',
    'Backups include your database, images, and all settings. They are stored as encrypted .zip files on your device.': 'Backups include your database, images, and all Masetting. They are stored as encrypted .zip files on your device.',
    'Balance': 'Bake',
    'Balance Due': 'Bake Due',
    'Built With': 'Built With',
    'Business / Shop Name': 'Biashara / Shop Jina',
    'Business Email Address': 'Biashara Email Address',
    'Business Information': 'Biashara Information',
    'Business Name': 'Biashara Jina',
    'Business Phone Number': 'Biashara Phone Number',
    'Business Profile': 'Biashara Profili',
    'Business Settings': 'Biashara Masetting',
    'Business settings saved successfully': 'Biashara Masetting saved successfully',
    'CANCEL': 'WACHA',
    'Cache': 'Cache',
    'Cache Management': 'Cache Management',
    'Cache cleared successfully': 'Cache cleared successfully',
    'Call': 'Call',
    'Camera': 'Camera',
    'Cancel': 'Wacha',
    'Centimeters (cm)': 'Centimeters (cm)',
    'Change': 'Change',
    'Change PIN or Password': 'Change Namba Siri or Nenosiri',
    'Choose Photo': 'Choose Photo',
    'Clear': 'Clear',
    'Clear Cache': 'Clear Cache',
    'Clear Cache?': 'Clear Cache?',
    'Clear Date Filter': 'Clear Date Filter',
    'Client & Garment': 'Mteja & Riga',
    'Close': 'Close',
    'Color': 'Color',
    'Coming Soon': 'Coming Soon',
    'Configure global garment measurements': 'Configure global Riga measurements',
    'Confirm Deletions': 'Confirm Deletions',
    'Confirm Reset': 'Confirm Reset',
    'Contact Support': 'Contact Support',
    'Continue': 'Continue',
    'Contributions': 'Contributions',
    'Could not launch WhatsApp': 'Could not launch WhatsApp',
    'Create Backup': 'Unda Backup',
    'Creating Identity': 'Creating Identity',
    'Creating Orders': 'Creating Maoda',
    'Creating backup...': 'Creating backup...',
    'Crop Photo': 'Crop Photo',
    'Currency': 'Currency',
    'Customer not found': 'Customer not found',
    'Customizing Your Theme': 'Customizing Your Theme',
    'DD/MM/YYYY': 'DD/MM/YYYY',
    'DELETE': 'FUTILIA',
    'Danger Zone': 'Danger Zone',
    'Dashboard Overview': 'Dashbodi Overview',
    'Data Export': 'Data Export',
    'Database': 'Database',
    'Database backed up successfully!': 'Database backed up successfully!',
    'Date Created': 'Date Created',
    'Date Format': 'Date Format',
    'Debug & Logging': 'Debug & Logging',
    'Debug Logging': 'Debug Logging',
    'Debug log viewer - coming soon': 'Debug log viewer - coming soon',
    'Default Labor Cost': 'Default Labor Cost',
    'Default Measurements': 'Default Measurements',
    'Default Measurements (Optional)': 'Default Measurements (Optional)',
    'Default Sort Order': 'Default Sort Order',
    'Default View': 'Default View',
    'Default cost per order used in the order wizard pricing step': 'Default cost per order used in the order wizard pricing step',
    'Default measurements have not been recorded.': 'Default measurements have not been recorded.',
    'Delete Everything': 'Futilia Everything',
    'Delete Note': 'Futilia Riba',
    'Delete all app data and reset to default settings. This cannot be undone.': 'Futilia all app data and reset to default Masetting. This cannot be undone.',
    'Discard': 'Discard',
    'Discard Changes?': 'Discard Changes?',
    'Discard Order?': 'Discard Order?',
    'Display Preferences': 'Display Preferences',
    'Display, interaction & default sort': 'Display, interaction & default sort',
    'Does not match. Try again.': 'Does not match. Try again.',
    'Due Date': 'Due Date',
    'Due Date:': 'Due Date:',
    'Due Soon': 'Due Soon',
    'ERROR: The route ': 'ERROR: The route',
    'EUR - Euro': 'EUR - Euro',
    'Edit': 'Tengeneza',
    'Edit Type': 'Tengeneza Type',
    'Edit/View': 'Edit/View',
    'Email': 'Email',
    'Email (Optional)': 'Email (Optional)',
    'Email Address': 'Email Address',
    'Enable App Lock (PIN)': 'Enable App Lock NAMBA SIRIN)',
    'Enable Biometrics': 'Enable Kidole',
    'English': 'English',
    'Enter PIN': 'Enter Namba Siri',
    'Enter measurements in inches. Existing profile data has been loaded automatically.': 'Enter measurements in inches. Existing Profili data has been loaded automatically.',
    'Enter notes here...': 'Enter Riba here...',
    'Example order number:': 'Example order number:',
    'Expected Total Amount': 'Expected Munde Amount',
    'Export CSV': 'Export CSV',
    'Export PDF': 'Export PDF',
    'Export as CSV': 'Export as CSV',
    'Export as JSON': 'Export as JSON',
    'Export completed successfully': 'Export Kazi Kwisha successfully',
    'Exporting CSV...': 'Exporting CSV...',
    'Exporting data as CSV...': 'Exporting data as CSV...',
    'Exporting data as JSON...': 'Exporting data as JSON...',
    'Factory Reset': 'Futa Zote',
    'Factory Reset?': 'Factory Reset?',
    'Female': 'Female',
    'Filter by Date': 'Filter by Date',
    'Financial Settings': 'Financial Masetting',
    'Financial Summary': 'Financial Summary',
    'Financials': 'Financials',
    'Font Size': 'Font Size',
    'Forgot?': 'Forgot?',
    'Full Name *': 'Full Jina *',
    'GBP - British Pound': 'GBP - British Pound',
    'Gallery': 'Gallery',
    'Garment not found': 'Riga not found',
    'Garments, Fabrics & Designs': 'Nguo, Vitambaa & Madesign',
    'Gender *': 'Gender *',
    'Generating PDF Report...': 'Generating PDF Report...',
    'Go Home': 'Go Base',
    'Grid': 'Grid',
    'Grid Density': 'Grid Density',
    'Haptic Feedback': 'Haptic Feedback',
    'Help': 'Help',
    'Help & User Guide': 'Help & User Guide',
    'ICHITO': 'ICHITO',
    'Images': 'Images',
    'Inches': 'Inches',
    'Interaction Preferences': 'Interaction Preferences',
    'Invalid recovery details': 'Invalid recovery details',
    'KES - Kenya Shilling': 'KES - Kenya Shilling',
    'Labor Cost': 'Labor Cost',
    'Language': 'Language',
    'Language & Format': 'Language & Format',
    'Language & Format settings saved': 'Language & Format Masetting saved',
    'Language, units, currency & dates': 'Language, units, currency & dates',
    'Last Chance!': 'Last Chance!',
    'List': 'List',
    'Location': 'Location',
    'Location (Optional)': 'Location (Optional)',
    'Location / City': 'Location / City',
    'Lock App Now': 'Lock App Now',
    'Loyal': 'Loyal',
    'MM/DD/YYYY': 'MM/DD/YYYY',
    'Male': 'Male',
    'Managing Customers': 'Managing Wateja',
    'Mark All Read': 'Mark All Read',
    'Material Cost': 'Material Cost',
    'Measurement Fields': 'Measurement Fields',
    'Measurement Types': 'Measurement Types',
    'Measurement Unit': 'Measurement Unit',
    'Measurements': 'Measurements',
    'Meeting Minutes / Notes': 'Meeting Minutes / Riba',
    'Meeting Title': 'Meeting Title',
    'Men': 'Men',
    'Most Used': 'Most Used',
    'Name': 'Jina',
    'Never': 'Never',
    'New Order': 'Oda Nya',
    'Newest': 'Newest',
    'Newest First': 'Newest First',
    'No Measurements': 'No Measurements',
    'No Notifications': 'No Rada Mpya',
    'No clients found': 'No Wateja found',
    'No contributions yet': 'No contributions yet',
    'No description': 'No Riba Kamili',
    'No designs found.': 'No Madesign found.',
    'No fabrics found.': 'No Vitambaa found.',
    'No garments found': 'No Nguo found',
    'No measurement types added yet.': 'No measurement types added yet.',
    'No notes found': 'No Riba found',
    'No orders found': 'No Maoda found',
    'No orders yet.': 'No Maoda yet.',
    'No payments recorded yet.': 'No payments recorded yet.',
    'No transactions found.': 'No transactions found.',
    'Note Settings': 'Riba Masetting',
    'Notes updated successfully': 'Riba updated successfully',
    'Notifications': 'Rada Mpya',
    'Number of Orders': 'Number of Maoda',
    'Oldest': 'Oldest',
    'Oldest First': 'Oldest First',
    'Open Source Licenses': 'Open Source Licenses',
    'Order Created!': 'Order Created!',
    'Order Number Prefix': 'Order Number Prefix',
    'Order Settings': 'Order Masetting',
    'Order not found': 'Order not found',
    'Orders': 'Maoda',
    'Owner Name': 'Owner Jina',
    'PIN setup successfully!': 'Namba Siri setup successfully!',
    'Password': 'Nenosiri',
    'Password must be at least 6 characters': 'Nenosiri must be at least 6 characters',
    'Password setup successfully!': 'Nenosiri setup successfully!',
    'Passwords do not match': 'Passwords do not match',
    'Payment History': 'Payment History',
    'Percentage tax applied to order totals (0 = no tax)': 'Percentage tax applied to order totals (0 = no tax)',
    'Performance': 'Performance',
    'Performance Mode': 'Performance Mode',
    'Personal & business information': 'Personal & Biashara information',
    'Phone': 'Phone',
    'Phone *': 'Phone *',
    'Phone Number': 'Phone Number',
    'Photo update coming soon': 'Photo update coming soon',
    'Pick Accent Color': 'Pick Accent Color',
    'Pinch to zoom, drag to position': 'Pinch to zoom, drag to position',
    'Please enter a code and select date of birth': 'Please enter a code and select date of birth',
    'Please pick a valid backup file.': 'Please pick a valid backup file.',
    'Please select a Due Date': 'Please select a Due Date',
    'Please select at least one measurement field.': 'Please select at least one measurement field.',
    'Preferences': 'Preferences',
    'Preferences Settings': 'Preferences Masetting',
    'Preferences are applied immediately to your view. Sort preferences affect how lists are displayed.': 'Preferences are applied immediately to your view. Sort preferences affect how lists are displayed.',
    'Privacy Policy': 'Privacy Policy',
    'Profile': 'Profili',
    'Profile Settings': 'Profili Masetting',
    'Profile saved successfully!': 'Profili saved successfully!',
    'Recent': 'Hivi Karibuni',
    'Recently Added': 'Recently Added',
    'Recipient (Who receives today?)': 'Recipient (Who receives today?)',
    'Record': 'Record',
    'Record Payment': 'Record Payment',
    'Recovery info saved': 'Recovery info saved',
    'Regular': 'Kawa',
    'Require PIN or Biometrics on startup': 'Require Namba Siri or Kidole on startup',
    'Required Measurements': 'Required Measurements',
    'Reset': 'Reset',
    'Restore': 'Restore',
    'Restore Backup?': 'Restore Backup?',
    'Restore Data': 'Restore Data',
    'Restore database from a backup file.': 'Restore database from a backup file.',
    'Restore from Backup': 'Restore from Backup',
    'Restoring backup...': 'Restoring backup...',
    'Restoring from backup will REPLACE all current data. This action cannot be undone.': 'Restoring from backup will REPLACE all current data. This action cannot be undone.',
    'Revenue Trend (Last 6 Months)': 'Revenue Trend (Last 6 Months)',
    'Role / Status': 'Role / Status',
    'Rotate Left': 'Rotate Left',
    'Rotate Right': 'Rotate Right',
    'Route Not Found': 'Route Not Found',
    'SMS': 'SMS',
    'Sample Text Preview': 'Sample Text Preview',
    'Save': 'Save',
    'Save Business Settings': 'Save Biashara Masetting',
    'Save Changes': 'Save Mabadiliko',
    'Save Note': 'Save Riba',
    'Save Password': 'Save Nenosiri',
    'Save Recovery Details': 'Save Recovery Details',
    'Save Settings': 'Save Masetting',
    'Save a copy of your database to local storage.': 'Save a copy of your database to local storage.',
    'Search by Order # or Client...': 'Saka by Order # or Mteja...',
    'Search by name or phone...': 'Saka by Jina or phone...',
    'Search designs...': 'Saka Madesign...',
    'Search fabrics...': 'Saka Vitambaa...',
    'Search garments...': 'Saka Nguo...',
    'Search notes...': 'Saka Riba...',
    'Search transactions...': 'Saka transactions...',
    'Security': 'Ulinzi',
    'Security & Backup': 'Ulinzi & Backup',
    'Security Settings': 'Ulinzi Masetting',
    'Select': 'Select',
    'Select Currency': 'Select Currency',
    'Select Date Format': 'Select Date Format',
    'Select Language': 'Select Language',
    'Select Unit': 'Select Unit',
    'Select a source for your profile photo': 'Select a source for your Profili photo',
    'Sermon Title': 'Sermon Title',
    'Set memorable date for password reset': 'Set memorable date for Nenosiri reset',
    'Set up recovery details to regain access if you forget your PIN or Password.': 'Set up recovery details to regain access if you forget your Namba Siri or Nenosiri.',
    'Settings': 'Masetting',
    'Setup Security': 'Setup Ulinzi',
    'Sheng': 'Sheng',
    'Show Full Order Numbers': 'Show Full Order Numbers',
    'Sort Customers By': 'Sort Wateja By',
    'Sort Notes By': 'Sort Riba By',
    'Sort Orders By': 'Sort Maoda By',
    'Sort: ': 'Sort:',
    'Special Instructions / Notes': 'Special Instructions / Riba',
    'Spent': 'Spent',
    'Start by adding your first customer and creating an order.': 'Start by adding your first customer and creating an order.',
    'Start typing...': 'Start typing...',
    'Status': 'Status',
    'Step 1: Select Client': 'Step 1: Select Mteja',
    'Step 2: Select Garment': 'Step 2: Select Riga',
    'Step 4: Materials & Design': 'Step 4: Materials & Design',
    'Step 5: Pricing & Scheduling': 'Step 5: Pricing & Scheduling',
    'Step 6: Review & Confirm': 'Step 6: Review & Confirm',
    'Storage Management': 'Storage Management',
    'TZS - Tanzania Shilling': 'TZS - Tanzania Shilling',
    'Taking Notes': 'Taking Riba',
    'Tap to change the primary accent color': 'Tap to change the primary accent color',
    'Tax Rate (%)': 'Tax Rate (%)',
    'The complete offline management system designed specifically for tailors.': 'The complete offline management system designed specifically for tailors.',
    'The feature ': 'The feature',
    'The order has been successfully recorded in the system.': 'The order has been successfully recorded in the system.',
    'Theme, colors, and gradients': 'Theme, colors, and gradients',
    'This item will be permanently deleted. This action cannot be undone. Please confirm by entering your PIN or using biometrics.': 'This item will be permanently deleted. This action cannot be undone. Please confirm by entering your Namba Siri or using Kidole.',
    'This will delete ALL data including customers, orders, notes, and images. This action CANNOT be undone.': 'This will Futilia ALL data including Wateja, Maoda, Riba, and images. This action CANNOT be undone.',
    'This will delete cached image thumbnails. The app will regenerate them on next use.': 'This will Futilia cached image thumbnails. The app will regenerate them on next use.',
    'Title': 'Title',
    'Title A-Z': 'Title A-Z',
    'Title Z-A': 'Title Z-A',
    'Toggle View': 'Toggle View',
    'Total Amount': 'Munde Amount',
    'Total Collected: ': 'Munde Collected:',
    'Total Expected': 'Munde Expected',
    'Total Paid': 'Munde Paid',
    'Total Spent': 'Munde Imetumika',
    'Total Used': 'Munde Used',
    'Transaction Details': 'Transaction Details',
    'Trial Date': 'Trial Date',
    'Trial Date:': 'Trial Date:',
    'Trial/Fitting Date': 'Trial/Fitting Date',
    'Type ': 'Type',
    'Type RESET': 'Type RESET',
    'UGX - Uganda Shilling': 'UGX - Uganda Shilling',
    'USD - US Dollar': 'USD - US Dollar',
    'Understanding Statistics': 'Understanding Mahesabu',
    'Unisex': 'Unisex',
    'Unlock': 'Unlock',
    'Upload': 'Upload',
    'Use Gradient Accents': 'Use Gradient Accents',
    'Use fingerprint or face unlock': 'Use fingerprint or face unlock',
    'User guide and support': 'User guide and support',
    'VIP': 'OGA',
    'Verify & Unlock': 'Verify & Unlock',
    'Version info and legal': 'Version info and legal',
    'View All': 'Ona Zote',
    'View Debug Logs': 'View Debug Logs',
    'View Order': 'View Order',
    'View Payment Details': 'View Payment Details',
    'View:': 'View:',
    'Warning: Advanced settings are for experienced users. Incorrect changes may cause unexpected behavior.': 'Warning: Advanced Masetting are for experienced users. Incorrect changes may cause unexpected behavior.',
    'Welcome to ICHITO': 'Welcome to ICHITO',
    'Welcome to ICHITO!': 'Welcome to ICHITO!',
    'What type of note?': 'What type of Riba?',
    'Women': 'Women',
    'Write notes here...': 'Write Riba here...',
    'Write sermon notes here...': 'Write sermon Riba here...',
    'YYYY-MM-DD': 'YYYY-MM-DD',
    'You have unsaved changes. Are you sure you want to discard them?': 'You have unsaved changes. Are you sure you want to discard them?',
    'e.g. 0712 345 678': 'e.g. 0712 345 678',
    'e.g. Chest, Waist, Length': 'e.g. Chest, Waist, Length',
    'e.g. Jane Muthoni': 'e.g. Jane Muthoni',
    'e.g. Nairobi CBD': 'e.g. Nairobi CBD',
    'e.g. jane@email.com': 'e.g. jane@email.com',
    'e.g., +254 712 345 678': 'e.g., +254 712 345 678',
    'e.g., Ichito Studios': 'e.g., Ichito Studios',
    'e.g., Nairobi, Kenya': 'e.g., Nairobi, Kenya',
    'e.g., contact@ichito.app': 'e.g., contact@ichito.app',
  };
}

class LanguageProvider extends ChangeNotifier {
  AppLanguage _currentLanguage = AppLanguage.english;
  String _currency = 'KES';
  String _measurementUnit = 'cm';
  String _dateFormat = 'dd/MM/yyyy';

  AppLanguage get currentLanguage => _currentLanguage;
  String get currency => _currency;
  String get measurementUnit => _measurementUnit;
  String get dateFormat => _dateFormat;

  String t(String key) {
    final map = _currentLanguage == AppLanguage.sheng 
      ? TranslationMaps.sheng 
      : TranslationMaps.en;
      
    return map[key] ?? TranslationMaps.en[key] ?? key;
  }

  void setLanguage(AppLanguage lang) {
    _currentLanguage = lang;
    notifyListeners();
  }

  void setCurrency(String currency) {
    _currency = currency;
    notifyListeners();
  }

  void setMeasurementUnit(String unit) {
    _measurementUnit = unit;
    notifyListeners();
  }

  void setDateFormat(String format) {
    _dateFormat = format;
    notifyListeners();
  }

  String formatCurrency(double amount, {bool showSymbol = true}) {
    final formatter = NumberFormat.currency(
      symbol: showSymbol ? '$_currency ' : '',
      decimalDigits: amount.truncateToDouble() == amount ? 0 : 2,
      locale: 'en_KE',
    );
    return formatter.format(amount);
  }

  String formatDate(DateTime? date, {bool includeTime = false}) {
    if (date == null) return '';
    String pattern = _dateFormat;
    if (includeTime) pattern += ' HH:mm';
    return DateFormat(pattern).format(date);
  }

  String formatTimeAgo(DateTime? date) {
    if (date == null) return '';
    final difference = DateTime.now().difference(date);
    
    if (difference.inDays > 7) return formatDate(date);
    if (difference.inDays > 0) return '${difference.inDays} days ago';
    if (difference.inHours > 0) return '${difference.inHours} hours ago';
    if (difference.inMinutes > 0) return '${difference.inMinutes} mins ago';
    return 'Just now';
  }

  String formatMeasurement(double value) {
    if (_measurementUnit == 'inches') {
      final inches = value / 2.54;
      return '${inches.toStringAsFixed(1).replaceAll(RegExp(r'\.0$'), '')} in';
    } else {
      return '${value.toStringAsFixed(1).replaceAll(RegExp(r'\.0$'), '')} cm';
    }
  }

  double parseMeasurementInput(String input) {
    final value = double.tryParse(input) ?? 0;
    if (_measurementUnit == 'inches') {
      return value * 2.54;
    }
    return value;
  }
}

extension StringLocalization on String {
  String t(BuildContext context) {
    try {
      return Provider.of<LanguageProvider>(context, listen: true).t(this);
    } catch (e) {
      return this;
    }
  }
}
